version: 2
registries:
  npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    registries:
      - npmjs
    allow:
      - dependency-type: production
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"
