/** Russian UI copy — single source for user-facing strings. */
export const ui = {
  appTitle: 'GeoIP Analytics (данные Главного радиочастотного центра России)',
  header: {
    yourIp: 'Ваш IP',
  },
  nav: {
    dashboard: 'Панель',
    table: 'Таблица',
    lookup: 'IP Lookup',
    apiDocs: 'API',
    admin: 'Admin',
  },
  rir: {
    notReady: 'Снимок RIR ещё не загружен. Дождитесь импорта или запустите его в Admin.',
    triggerImport: 'Импортировать RIR+IANA',
    statusTitle: 'RIR registry (delegated)',
    lastSuccess: 'Последний успех',
    snapshotDate: 'Дата снимка',
    rowCount: 'Строк',
  },
  lookup: {
    sectionCity: 'City',
    sectionCountry: 'Country',
    sectionAsn: 'ASN',
    sectionMap: 'Карта',
  },
  apiDocs: {
    title: 'External IP Lookup API',
    subtitle: 'HTTP API для получения геоданных по IP-адресу. Используется единый API-ключ проекта.',
    authTitle: 'Аутентификация',
    authBody:
      'Передайте заголовок X-API-Key с ключом «API-ключ External IP Lookup» из Admin → API и безопасность. Ключ не показывается на этой странице — скопируйте при Generate в Admin.',
    adminLink: 'Admin → API и безопасность → API-ключ External IP Lookup',
    openDocsLink: 'Документация External IP Lookup API',
    endpointTitle: 'Endpoint',
    requestTitle: 'Тело запроса (JSON)',
    requestIntro: 'Content-Type: application/json',
    fieldIp: 'IPv4 или IPv6 (обязательно)',
    fieldInclude:
      'Опционально: массив city, country, asn. Если не указан — возвращаются все секции.',
    responseTitle: 'Ответ',
    responseIntro: 'JSON с полями ip, city, country, asn и meta (datasetDate, queriedAt).',
    errorsTitle: 'Коды ошибок',
    error401: '401 — отсутствует или неверный X-API-Key (при включённом API auth)',
    error400: '400 — невалидный IP-адрес',
    error422: '422 — ошибка валидации тела запроса',
    error429: '429 — превышен rate limit (Admin → API)',
    examplesTitle: 'Примеры',
    adminOpsTitle: 'Для администраторов (production)',
    adminOpsAuth:
      'Включите API auth enabled в Admin → API. При утечке ключа — сгенерируйте новый и перезапустите geoip_web.',
    adminOpsNpm:
      'В NPM создайте custom location /api/v1/lookup без Access List и добавьте proxy_set_header X-GeoIP-Client-Auth 1;',
    adminOpsRateLimit: 'Лимит запросов настраивается в Admin → API (rate limit).',
    copy: 'Копировать',
    copied: 'Скопировано',
  },
  browse: {
    cityTab: 'City blocks',
    countryTab: 'Country blocks',
    asnTab: 'ASN blocks',
    rirTab: 'RIR registry',
    resetFilters: 'Сбросить фильтры',
    slowSortBanner:
      'Сортировка по стране или городу на полной таблице (~20M строк) может занимать несколько секунд. Добавьте фильтр ISO страны = RU для ускорения до миллисекунд.',
    slowSortBannerCountry:
      'Сортировка по стране на полной таблице может занимать несколько секунд. Добавьте фильтр ISO страны = RU для ускорения.',
    ruPartialSortOverrideBanner:
      'На RU-подвыборке (~10M строк) сортировка по стране выполняется по полю Network — в partial MV нет rank-колонки country_name.',
    offsetOnlySortBanner:
      'При текущей сортировке прокрутка ограничена (OFFSET). Для быстрой навигации используйте сортировку по Network, Country или City.',
    estimatedCountBanner:
      'При ASN-фильтре точное число строк не считается — внизу таблицы показана оценка. Уточните другие фильтры для exact count.',
    facetSampleBanner:
      '≈ Счётчики из выборки — приблизительные. Уточните фильтры для точных facet counts.',
    noResultsFound: 'Ничего не найдено. Измените фильтры или сбросьте их.',
    facetSampleTimedOut:
      'Выборка ограничена по времени — показаны частичные результаты. Уточните фильтры или поиск.',
    exportCsv: 'Экспорт CSV',
    exportCsvHint: 'Скачивает ZIP-архив с CSV всей выборки по текущим фильтрам (не только строки на экране).',
    exportInProgress: 'Формирование CSV и архива…',
    exportDownloading: 'Скачивание архива…',
    exportFailed: 'Не удалось сформировать экспорт',
    exportRowLimit: 'Слишком много строк для экспорта. Сузьте фильтры или увеличьте лимит в Admin.',
    exportRowLimitExceeded: (estimatedRows: number, maxRows: number) =>
      `В выборке ${estimatedRows.toLocaleString('ru-RU')} строк — больше лимита экспорта (${maxRows.toLocaleString('ru-RU')}). Увеличьте «Max rows» в Admin или сузьте фильтры.`,
    exportRowLimitBlocked: (estimatedRows: number, maxRows: number) =>
      `Экспорт недоступен: ${estimatedRows.toLocaleString('ru-RU')} строк при лимите ${maxRows.toLocaleString('ru-RU')}. Измените Max rows в Admin.`,
    exportNotReady: 'Данные ещё загружаются. Повторите позже.',
    exportTimedOut: 'Превышено время ожидания экспорта. Попробуйте сузить фильтры.',
  },
  filters: {
    network: 'Network',
    prefix_len: 'Prefix',
    country_iso_code: 'ISO страны',
    country_name: 'Country',
    city_name: 'City',
    subdivision_1_name: 'Region',
    asn: 'ASN',
    asn_org: 'ASN Org',
    registry: 'RIR',
    resource_type: 'Type',
    range_text: 'Range',
    cc: 'CC',
    status: 'Status',
    allocated_at: 'Allocated',
    opaque_id: 'Opaque ID',
    ip_family: 'Family',
  },
  dashboard: {
    systemStatus: 'Подсистема ГРЧЦ',
    activeDataset: 'Активный датасет ГРЧЦ',
    dataVolume: 'Объем данных датасета ГРЧЦ',
    recentImports: 'Последние импорты',
    colPlane: 'Плоскость',
    planeGrchc: 'ГРЧЦ',
    planeRir: 'RIR+IANA',
    rirRegistriesCard: 'Реестры RIR / IANA',
    rirActiveDataset: 'Активный датасет RIR / IANA',
    rirDataVolume: 'Объем данных датасета RIR / IANA',
    rirTotalRows: 'Всего диапазонов',
    rirRegistryRipencc: 'RIPE NCC',
    rirRegistryArin: 'ARIN',
    rirRegistryApnic: 'APNIC',
    rirRegistryAfrinic: 'AFRINIC',
    rirRegistryLacnic: 'LACNIC',
    rirRegistryIana: 'IANA',
    importBenchmark: 'Benchmark последнего импорта',
    importDetail: 'Детали импорта',
    statusReady: 'Готово',
    statusDegraded: 'Деградировано',
    statusNotReady: 'Не готово',
    statusInitializing: 'Инициализация',
    initializingBanner:
      'Идёт подготовка данных — часть функций временно недоступна. Обычно занимает несколько минут.',
    mvStatusReady: 'готово',
    mvStatusRefreshing: 'подготовка…',
    mvStatusUnavailable: 'недоступно',
    checkDb: 'БД',
    checkDataset: 'Датасет',
    checkMv: 'MV',
    checkIndexes: 'Индексы',
    checkAsn: 'ASN mapping',
    checkDbLabel: 'База данных',
    checkDatasetLabel: 'Датасет',
    checkMvLabel: 'Представления для запросов',
    checkIndexesLabel: 'Индексы',
    checkAsnLabel: 'Сопоставление ASN',
    checkDbOk: 'Подключена',
    checkDbFail: 'Недоступна',
    checkDatasetOk: 'Загружен',
    checkDatasetFail: 'Не загружен',
    checkMvOk: 'Готовы',
    checkMvPending: 'Подготовка…',
    checkMvFail: 'Не готовы',
    checkIndexesOk: 'Созданы',
    checkIndexesFail: 'Отсутствуют',
    checkAsnOk: 'Готово',
    checkAsnFail: 'Не готово',
    mvStatus: 'Статус MV',
    fingerprint: 'Fingerprint',
    activeImport: 'Активный import',
    nextImport: 'Следующий import',
    serverTime: 'Время на сервере',
    cityBlocks: 'City blocks',
    cityLocations: 'City locations',
    ruCityBlocks: 'RU city blocks',
    asnBlocks: 'ASN blocks',
    ipv4Addresses: 'Уникальные IPv4',
    activated: 'Активирован',
    colId: 'ID',
    colDate: 'Дата',
    colStatus: 'Статус',
    colTrigger: 'Источник',
    colWall: 'Wall',
    colStarted: 'Начало',
    colStep: 'Шаг',
    colDuration: 'Длительность',
    colRows: 'Строки',
    colDetails: 'Детали',
    viewSteps: 'Шаги',
    hideSteps: 'Скрыть',
    wallTime: 'Wall',
    runId: 'run',
    rirRegistries: 'RIR registries',
    ianaDelegated: 'IANA delegated',
    rirSnapshot: 'Снимок',
    rirLastSuccess: 'Последний успех',
    rirRows: 'Строк',
    rirImportStatus: 'Импорт',
    rirBrowse: 'Открыть таблицу',
    rirNotLoaded: 'Снимок ещё не загружен',
    rirStatusReady: 'Готово',
    rirStatusImporting: 'Импорт…',
    rirStatusFailed: 'Ошибка',
    rirStatusUnavailable: 'Нет данных',
    rirByRegistry: 'По реестрам',
    rirByStatus: 'По status',
    rirLastError: 'Ошибка',
  },
  systemBanner: {
    headerStatus: 'Система',
    titleUnavailable: 'Не удалось проверить состояние системы',
    titleNotReady: 'Система не готова к работе',
    titleDegraded: 'Система работает с ограничениями',
    titleInitializing: 'Инициализация',
    initializingHint:
      'Идёт подготовка данных — часть функций временно недоступна. Обычно занимает несколько минут.',
    importRunning: 'Выполняется импорт датасета — часть функций может быть недоступна.',
    processGrchcImport: 'ГРЧЦ: выполняется импорт датасета',
    processGrchcMv:
      'ГРЧЦ: подготовка материализованных представлений (таблица, lookup и экспорт временно недоступны)',
    processGrchcAsn: 'ГРЧЦ: сопоставление ASN ещё не готово',
    processRirImport: 'RIR+IANA: выполняется импорт',
    processRirFailed: 'RIR+IANA: ошибка импорта',
    detailsLink: 'Подробнее на Dashboard',
    datasetError: 'Датасет: ошибка загрузки',
  },
  setup: {
    title: 'Настройка системы',
    optional: 'опционально',
    openStep: 'Настроить',
    allBlockingDone: 'Обязательные шаги выполнены — система готова к работе.',
    grchcHelpTitle: 'Как получить доступ к ЛК ГРЧЦ',
    grchcHelpBody:
      'Зарегистрируйтесь на сайте ГРЧЦ и получите учётные данные личного кабинета GeoIP. Укажите email и пароль здесь, сохраните, нажмите «Проверить ГРЧЦ», затем «Импортировать ГРЧЦ» на вкладке Обзор.',
    mapsHelpTitle: 'Google Maps Embed API',
    mapsHelpBody:
      'Создайте ключ в Google Cloud Console с включённым Maps Embed API. Ограничьте ключ по HTTP referrer вашего домена. Ключ подхватывается без пересборки web.',
    mapsConfigureLink: 'Настроить в Admin → Интеграции',
    grchcSavedGoImport:
      'Учётные данные ГРЧЦ сохранены. Следующий шаг — «Импортировать ГРЧЦ» на вкладке Обзор.',
    autoImportHelpTitle: 'Автоимпорты при первичной настройке',
    autoImportHelpBody:
      'После ручного импорта ГРЧЦ и RIR+IANA включите оба автоимпорта и задайте ежедневное время загрузки. По умолчанию автоимпорты выключены — без этого шага чеклист первичной настройки не завершится.',
  },
  datasetBadge: 'Датасет',
  datasetMenu: {
    grchc: 'Датасет ГРЧЦ',
    ripe: 'Датасет RIPE',
    arin: 'Датасет ARIN',
    apnic: 'Датасет APNIC',
    afrinic: 'Датасет AFRINIC',
    lacnic: 'Датасет LACNIC',
    iana: 'Датасет IANA',
  },
  admin: {
    title: 'Администрирование',
    loginTitle: 'Вход в Admin',
    setupTitle: 'Первичная настройка',
    setupHint: 'Задайте локальный логин и пароль администратора.',
    loginAction: 'Войти',
    setupAction: 'Создать admin',
    setupApiKeyTitle: 'API-ключ External IP Lookup',
    setupApiKeyHint:
      'Обязательный шаг первичной настройки. Ключ используется для External IP Lookup API и внутренних запросов SPA. Скопируйте ключ сейчас — после сохранения он будет скрыт.',
    setupApiKeyAction: 'Сохранить ключ',
    setupApiKeySaved: 'Ключ сохранён. Перезапустите geoip_web после деплоя, если proxy.env не обновился автоматически.',
    logout: 'Выйти',
    loading: 'Загрузка настроек…',
    saved: 'Настройки сохранены',
    saveSection: 'Сохранить секцию',
    testGrchc: 'Проверить ГРЧЦ',
    testRir: 'Проверить RIR+IANA',
    triggerImport: 'Импортировать ГРЧЦ',
    triggerRirImport: 'Импортировать RIR+IANA',
    importQueued: 'Импорт датасета ГРЧЦ поставлен в очередь',
    rirImportQueued: 'Импорт RIR+IANA поставлен в очередь',
    rirProbeOk: 'RIR+IANA доступны',
    rirProbeFailed: 'Проверка RIR+IANA не прошла',
    rirProbeInProgress: 'Проверка RIR+IANA…',
    resetRirImport: 'Сбросить зависший импорт',
    resetRirImportDone: 'Зависший импорт RIR сброшен',
    wipeData: 'Удалить данные',
    wipeDataConfirm:
      'Удалить все датасеты ГРЧЦ и RIR, историю импортов, экспорты и кэш? Это действие нельзя отменить.',
    wipeDataDone: 'Данные удалены',
    wipeDataHint: 'Полная очистка датасетов, истории импортов и экспортов. Конфигурация Admin сохранится.',
    rirActiveImport: 'Активный run',
    username: 'Логин',
    password: 'Пароль',
    newPassword: 'Новый пароль',
    currentPassword: 'Текущий пароль',
    confirmPassword: 'Подтверждение пароля',
    updatedAt: 'Обновлено',
    importTime: 'Время ежедневного импорта ГРЧЦ',
    rirImportTime: 'Время ежедневного импорта RIR+IANA',
    importCronEnabled: 'Автоимпорт ГРЧЦ',
    rirImportCronEnabled: 'Автоимпорт RIR+IANA',
    zipCacheEnabled: 'Кэш ZIP ГРЧЦ',
    skipUnchangedDataset: 'Пропускать неизменённый датасет ГРЧЦ',
    displayTimezone: 'Часовой пояс',
    displayTimezoneHint:
      'Все даты и время в интерфейсе, а также время автоимпорта ниже, указываются в этом часовом поясе (IANA).',
    autoImportHint: 'Время автоимпорта — ежедневно, в выбранном выше часовом поясе.',
    overviewHint: 'Статус локального config store и быстрые операции.',
    reloadHints: 'Поля, требующие перезапуска сервисов',
    infraHint: 'Параметры инфраструктуры (Postgres, compose) меняются через Portainer и не хранятся в admin store.',
    apiKeyExternalLookup: 'API-ключ External IP Lookup',
    apiKeyExternalLookupHint:
      'Заголовок X-API-Key для внешних интеграций (см. /api-docs). После сохранения ключ скрыт — скопируйте при Generate.',
    importApiKey: 'Import API key',
    sections: {
      overview: 'Обзор',
      general: 'Общие',
      grchc: 'ГРЧЦ / Import',
      rir: 'RIR registry',
      api: 'API и безопасность',
      adminAccess: 'Admin доступ',
      export: 'Export',
      performance: 'Производительность',
      integrations: 'Интеграции',
      logging: 'Логирование',
      infra: 'Инфраструктура',
    },
  },
} as const;

export function importStatusLabel(status: string): string {
  const labels: Record<string, string> = {
    queued: 'в очереди',
    running: 'выполняется',
    validating: 'валидация',
    swapping: 'swap',
    refreshing_mv: 'обновление MV',
    succeeded: 'успех',
    failed: 'ошибка',
  };
  return labels[status] ?? status;
}

export function importTriggerLabel(trigger: string): string {
  const labels: Record<string, string> = {
    manual: 'вручную',
    cron: 'cron',
    api: 'API',
  };
  return labels[trigger] ?? trigger;
}
